// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlbd16fDiHcrQQtzz0Xen0xItoeJMlWuY',
    appId: '1:524330395598:web:326ced0246dcbe3e9d2d9f',
    messagingSenderId: '524330395598',
    projectId: 'catalogo-d80e2',
    authDomain: 'catalogo-d80e2.firebaseapp.com',
    storageBucket: 'catalogo-d80e2.firebasestorage.app',
    measurementId: 'G-GPBE2QPDBS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDSUt5aHolid2n7O65QyOiwdtcBkdDk38',
    appId: '1:524330395598:android:95bcf2c908a406d99d2d9f',
    messagingSenderId: '524330395598',
    projectId: 'catalogo-d80e2',
    storageBucket: 'catalogo-d80e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDCPoHy6RKG3VTxBRGOE1TtZoaQjpi61M',
    appId: '1:524330395598:ios:1283bb6577cf63ad9d2d9f',
    messagingSenderId: '524330395598',
    projectId: 'catalogo-d80e2',
    storageBucket: 'catalogo-d80e2.firebasestorage.app',
    iosBundleId: 'com.example.ldswUtilizandoWidgets',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDCPoHy6RKG3VTxBRGOE1TtZoaQjpi61M',
    appId: '1:524330395598:ios:1283bb6577cf63ad9d2d9f',
    messagingSenderId: '524330395598',
    projectId: 'catalogo-d80e2',
    storageBucket: 'catalogo-d80e2.firebasestorage.app',
    iosBundleId: 'com.example.ldswUtilizandoWidgets',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlbd16fDiHcrQQtzz0Xen0xItoeJMlWuY',
    appId: '1:524330395598:web:7ab53b8bd524bd219d2d9f',
    messagingSenderId: '524330395598',
    projectId: 'catalogo-d80e2',
    authDomain: 'catalogo-d80e2.firebaseapp.com',
    storageBucket: 'catalogo-d80e2.firebasestorage.app',
    measurementId: 'G-NYWCEXBLW2',
  );
}
